### PR TITLE
dev(narugo): add danbooru tag filter for danbooru source

### PR DESCRIPTION
**Pull request by narugo1992**
```python
from waifuc.export import TextualInversionExporter
from waifuc.source import DanbooruSource

s = DanbooruSource(
    ['surtr_(arknights)', 'solo'],
    tag_domains=['general', 'meta'],
    # tag_domains=['general', 'character', 'copyright', 'artist', 'meta'],
)
s.attach(

)[:10].export(TextualInversionExporter('test_ti'))

```

### CODE REVIEW

**Comment by narugo1992** [comment]
#42 @wochenlong cc

**Comment by wochenlong** [comment]
@narugo1992  进行了测试，我这里无法把艺术家名称过滤掉。
我切换到对应的分支：
```
PS E:\waifuc> git branch -r
  origin/HEAD -> origin/main
  origin/dev/danbooru
  origin/gh-pages
  origin/main
PS E:\waifuc> git checkout -b dev/danbooru origin/dev/danbooru
Switched to a new branch 'dev/danbooru'
branch 'dev/danbooru' set up to track 'origin/dev/danbooru'.
```

这个是我的代码：
```
from waifuc.action import *
from waifuc.export import *
from waifuc.source import *

if __name__ == "__main__":
    s = DanbooruSource(["souryuu_asuka_langley","solo"])
    tag_domains=['general', 'character'],
    s.attach(
        ModeConvertAction("RGB", "white"),
        NoMonochromeAction(),  # 
        ClassFilterAction(["illustration", "bangumi"]),  
   CCIPAction(),
        AlignMinSizeAction(1024),
        FilterSimilarAction(),
        RandomFilenameAction(),
        FirstNSelectAction(2000),  
        FileExtAction(ext='.webp', quality=90)  
    ).export(
         TextualInversionExporter(r"E:\data\eva\souryuu\1_souryuu")
    ) 

```
我爬取到的其中一张图片：
eb83eb0e0dde702cd95f0eead1df90650739065d
他的TAG是：
```1girl, absurdres, blonde_hair, blue_eyes, bodysuit, cowboy_shot, evangelion:_3.0_you_can_\(not\)_redo, eyepatch, gloves, highres, interface_headset, latex, latex_bodysuit, latex_gloves, long_hair, neon_genesis_evangelion, pilot_suit, plugsuit, rebuild_of_evangelion, red_bodysuit, red_gloves, saaal653, simple_background, solo, souryuu_asuka_langley, twintails, v, white_background```

其中，saaal653为艺术家名字。
此作品的链接：https://danbooru.donmai.us/posts/7221695?q=souryuu_asuka_langley

**Comment by narugo1992** [comment]
@wochenlong ahh, what the xxx

u are using

```python
s = DanbooruSource(["souryuu_asuka_langley","solo"])
    tag_domains=['general', 'character'],
```

but it should be

```python
s = DanbooruSource(
    ["souryuu_asuka_langley","solo"]
    tag_domains=['general', 'character'],
)
```

**Comment by wochenlong** [comment]
@narugo1992 I tested it, there is no problem. It's just that I made a syntax error in my code (escaping)

**Pull request merged**
